### ISSUE TITLE
help

### ISSUE THREAD

**Issue by DDxk369** [lucidrains/glom-pytorch#2]
Hello, when I tried to reproduce your model, I got this error. I'm not sure how to correct it， can y help me?

Traceback (most recent call last):
  File "main.py", line 172, in <module>
    outputs = custom_model(images,iters = 12)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/class/glom_pytorch/glom_pytorch.py", line 109, in forward
    consensus = self.attention(levels)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/class/glom_pytorch/glom_pytorch.py", line 49, in forward
    sim.masked_fill_(self_mask, TOKEN_ATTEND_SELF_VALUE)
RuntimeError: Expected object of scalar type Bool but got scalar type Float for argument #2 'mask' in call to _th_masked_fill_bool_

**Comment by lucidrains** [comment]
oops! fixed in the latest commit!
